import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const context=await browser.newContext({viewport:{width:1600,height:1200}});
 const page=await context.newPage();
 const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});
 page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE ERROR',m.text());});
 await page.goto('http://127.0.0.1:8765/twin/');
 await page.getByText(/separate assembly pieces loaded/).waitFor({timeout:60000});
 await page.screenshot({path:'U:/inmoov/hardware/twin-preview.png',fullPage:true});
 console.log('Loaded:',await page.locator('#loaded-count').innerText());
 console.log('Canvas:',await page.locator('canvas').evaluate(e=>({width:e.width,height:e.height,hidden:document.hidden})));
 assert.equal(await page.locator('.part').count(),76);
 assert.equal(await page.locator('.channel').count(),16);
 await page.getByRole('textbox',{name:'Search parts'}).fill('Jaw');
 assert.equal(await page.locator('.part:visible').count(),7);
 await page.getByRole('textbox',{name:'Search parts'}).fill('');
 await page.getByRole('button',{name:'Parts layout',exact:true}).click();
 await page.screenshot({path:'U:/inmoov/hardware/twin-parts-preview.png'});
 await page.getByRole('button',{name:'Assembly draft',exact:true}).click();
 await page.getByRole('button',{name:'Isolate',exact:true}).click();
 await page.screenshot({path:'U:/inmoov/hardware/twin-isolate-preview.png'});
 await page.getByRole('button',{name:'Show all',exact:true}).click();
 await page.locator('#ch-11').fill('1500');
 assert.match(await page.locator('#ch-11').locator('..').innerText(),/1500 µs/);
 await page.getByRole('button',{name:'Neutral',exact:true}).click();
 assert.equal(await page.locator('#ch-11').inputValue(),'1300');
 await page.locator('#live').check();
 const sender=await page.context().newPage();await sender.goto('http://127.0.0.1:8765/');
 await sender.evaluate(()=>{const b=new BroadcastChannel('inmoov-twin-commands-v1');b.postMessage({command:'C11 1600'});b.close();});
 await page.waitForFunction(()=>document.querySelector('#ch-11').value==='1600');
 assert.equal(await sender.getByRole('button',{name:'Calibrate',exact:true}).count(),16);
 await sender.close();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Fit view',exact:true}).click();
 await page.screenshot({path:'U:/inmoov/hardware/twin-mobile-preview.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);
 console.log('Interactions passed');
}finally{await browser.close();}
